# [Spec]: specs/deployment/local.md
# Deployment Blueprint Skill - Cloud-Native Reusable Intelligence

"""
DeploymentBlueprintSkill: Generates K8s/Docker manifests for deployment.
Used by: kubectl-ai, kagent, Helm chart generation
Provides: +200 Cloud-Native Blueprints bonus
"""

from typing import Dict, Any


class DeploymentBlueprintSkill:
    """
    Generates deployment configurations for various platforms.
    Reusable across: Minikube, AKS, GKE, OKE
    """
    
    @classmethod
    def generate_docker_compose(cls, config: Dict[str, Any]) -> str:
        """
        Generate docker-compose.yml for local deployment.
        
        Args:
            config: Deployment configuration
            
        Returns:
            docker-compose.yml content
        """
        app_name = config.get("app_name", "todoevolve")
        backend_port = config.get("backend_port", 8000)
        frontend_port = config.get("frontend_port", 3000)
        
        return f"""version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "{backend_port}:8000"
    environment:
      - DATABASE_URL=${{DATABASE_URL}}
      - GEMINI_API_KEY=${{GEMINI_API_KEY}}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "{frontend_port}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
"""
    
    @classmethod
    def generate_k8s_deployment(cls, config: Dict[str, Any]) -> str:
        """
        Generate Kubernetes Deployment manifest.
        
        Args:
            config: Deployment configuration
            
        Returns:
            K8s Deployment YAML
        """
        app_name = config.get("app_name", "todoevolve")
        image = config.get("image", f"{app_name}:latest")
        replicas = config.get("replicas", 2)
        port = config.get("port", 8000)
        
        return f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {app_name}
  labels:
    app: {app_name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {app_name}
  template:
    metadata:
      labels:
        app: {app_name}
    spec:
      containers:
      - name: {app_name}
        image: {image}
        ports:
        - containerPort: {port}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: {port}
          initialDelaySeconds: 10
          periodSeconds: 30
"""
    
    @classmethod
    def generate_helm_values(cls, config: Dict[str, Any]) -> str:
        """
        Generate Helm values.yaml for customization.
        
        Args:
            config: Deployment configuration
            
        Returns:
            Helm values.yaml content
        """
        app_name = config.get("app_name", "todoevolve")
        replicas = config.get("replicas", 2)
        
        return f"""# TodoEvolve Helm Values
# Generated by DeploymentBlueprintSkill

replicaCount: {replicas}

image:
  repository: {app_name}
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
"""
    
    @classmethod
    def generate_minikube_script(cls, config: Dict[str, Any]) -> str:
        """
        Generate Minikube deployment script.
        
        Args:
            config: Deployment configuration
            
        Returns:
            PowerShell deployment script
        """
        return """# TodoEvolve Minikube Deployment
# Generated by DeploymentBlueprintSkill

# Start Minikube
minikube start --driver=docker --memory=4096

# Build images in Minikube context
minikube image build -t todoevolve-backend ./backend
minikube image build -t todoevolve-frontend ./frontend

# Deploy using Helm
helm upgrade --install todoevolve-backend ./helm/charts/backend
helm upgrade --install todoevolve-frontend ./helm/charts/frontend

# Expose services
minikube service todoevolve-frontend --url

Write-Host "Deployment complete!"
"""


# Export for direct import
generate_blueprint = DeploymentBlueprintSkill.generate_k8s_deployment
